export const types = {
  IS_LOADING_AUTH: 'IS_LOADING_AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  GET_ERRORS: 'GET_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  START_GET_ALL_EVENT_TYPES: 'START_GET_ALL_EVENT_TYPES',
  GET_ALL_EVENT_TYPES: 'GET_ALL_EVENTS',
  GET_SINGLE_EVENT_TYPE: 'GET_SINGLE_EVENT_TYPE',
};
