import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Simba | Cal</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex flex-row items-center justify-center'>
        <a href='/auth/register' className='mx-2'>
          Signup
        </a>
        |
        <a href='/auth/login' className='mx-2'>
          Login
        </a>
        To Genesis Mission
      </div>
    </div>
  );
};

export default Home;
