name: Build and release fs-simba-cal web application
on: [push, pull_request]
jobs:
  build-project:
    name: Build fs-simba-cal web application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: yarn install
      - name: Build static website
        run: yarn build
      - name: Upload static website
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/
